#!/usr/bin/env node
/**
 * Propagate the shared modules in shared/ into every game.
 *
 * The games are meant to stay self-contained — one folder, open it and it runs —
 * so none of them import across folder boundaries at runtime. city-storm is
 * already a multi-file module app and just gets a copy of the file; the two
 * single-file games get the source spliced into their HTML between the marker
 * comments, with `export ` stripped since it is not a module boundary there.
 *
 * Run from the repo root:  node tools/sync-shared.mjs [--check]
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const A = (...p) => path.join(ROOT, ...p);

/**
 * Each kit names its source, the marker pair that brackets it in an inlined
 * target, the namespace it is exposed under, verbatim copies, and inline
 * targets.
 */
const KITS = [
  {
    name: 'photoreal',
    src: A('shared', 'photoreal.js'),
    ns: 'PR',
    copies: [A('city-storm', 'photoreal.js'), A('android', 'app', 'src', 'main', 'assets', 'city', 'photoreal.js')],
    inline: [
      A('tank-battle', 'index.html'),
      A('falcon-strike', 'index.html'),
      A('android', 'app', 'src', 'main', 'assets', 'tank', 'index.html'),
      A('android', 'app', 'src', 'main', 'assets', 'falcon', 'index.html'),
    ],
  },
  {
    name: 'touch',
    src: A('shared', 'touch.js'),
    ns: 'TC',
    // The tank build predates this module and has its own control layer that is
    // already proven on a device; it is deliberately not a target.
    copies: [A('android', 'app', 'src', 'main', 'assets', 'city', 'touch.js')],
    inline: [A('android', 'app', 'src', 'main', 'assets', 'falcon', 'index.html')],
  },
];

let stale = 0;
const write = (file, next) => {
  const prev = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (prev === next) return console.log(`  up to date  ${path.relative(ROOT, file)}`);
  stale++;
  if (check) return console.log(`  STALE       ${path.relative(ROOT, file)}`);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, next);
  console.log(`  written     ${path.relative(ROOT, file)}`);
};

for (const kit of KITS) {
  const source = fs.readFileSync(kit.src, 'utf8');
  const BEGIN = `/* === BEGIN ${kit.name} kit (generated by tools/sync-shared.mjs) === */`;
  const END = `/* === END ${kit.name} kit === */`;

  // Inlined copies are wrapped in an IIFE that exposes only the exported names.
  // Splicing a module body straight into a game's script would drop internals
  // like `fbm` and `texture` into its scope — and both single-file games
  // already define an `fbm` of their own, which is a duplicate-declaration
  // SyntaxError.
  const exported = [...source.matchAll(/^export (?:function|const) ([A-Za-z0-9_$]+)/gm)].map((m) => m[1]);
  if (!exported.length) {
    console.error(`no exports found in ${path.relative(ROOT, kit.src)}`);
    process.exit(1);
  }
  const body = [
    BEGIN,
    `const ${kit.ns} = (() => {`,
    source.replace(/^export /gm, ''),
    `return { ${exported.join(', ')} };`,
    '})();',
    END,
  ].join('\n');

  const header = `/* GENERATED — do not edit. Source: shared/${kit.name}.js (tools/sync-shared.mjs). */\n`;
  for (const file of kit.copies) write(file, header + source);

  for (const file of kit.inline) {
    if (!fs.existsSync(file)) { console.log(`  skipped     ${path.relative(ROOT, file)} (absent)`); continue; }
    const html = fs.readFileSync(file, 'utf8');
    const a = html.indexOf(BEGIN), b = html.indexOf(END);
    if (a === -1 || b === -1) {
      console.log(`  no markers  ${path.relative(ROOT, file)} — needs ${BEGIN}`);
      stale++;
      continue;
    }
    write(file, html.slice(0, a) + body + html.slice(b + END.length));
  }
}

if (check && stale) {
  console.error(`\n${stale} target(s) out of date — run: node tools/sync-shared.mjs`);
  process.exit(1);
}
console.log(stale ? '\nsynced' : '\nall targets already current');
